### ISSUE TITLE
Resources do not persist

### ISSUE THREAD

**Issue by veteranmina** [recursivetree/seat-info#2]
v1.4.1 - Seat Info

In the current state with how the plugin is written when docker is used for SeAT any resources uploaded through the plugin are lost when the containers are cycled. The database record still exists, however is unable to locate the resource link.

This results in requiring me to re-upload and fix the affected articles each time. A persisted storage volume is needed in the case of SeAT docker installations, not sure if bare metal installs occur this same issue.

**Comment by recursivetree** [comment]
I used the Laravel File Storage with the default disk to store the resource files: 
https://laravel.com/docs/6.x/filesystem
I suspect that the default disk is just the file system. You might get around it by configuring the default disk manually to something that is persistent.

If you got it working, let me know and I might add it to the documentation.

**Comment by veteranmina** [comment]
In docker environments this will not work unfortunately. This is due to when the container is cycled the filesystem is wiped clean slate.

Use of a volume in docker-compose-override.yml (recommended so to not edit the docker-compose.yml file) will need to be added in order to persist through container refreshes

**Comment by recursivetree** [comment]
Yes, you will have to edit the docker-compose.yml file with an override for the storage configuration file. If you know what you are doing, it shouldn't be an issue(it is required to increase file size upload limits for seat-info anyways).

Of course it is suboptimal, but there is no way to create a persistent volume from within a seat plugin (or it is just as hacky as editing the docker-compose file).

You can also try to open an issue in the seat core to have the storage configured persistently with docker.

**Comment by veteranmina** [comment]
There is a current location that SeAT does view for volume storage if added in the docker-compose.yml file, maybe you can use it as well? It is currently used for when custom layouts are set for styling. 

/var/www/seat/public/

**Comment by recursivetree** [comment]
I added some hints to the documentation, but there is only so much I can do, it is rather a core issue. Closing this
