### ISSUE TITLE
shipfit javascript package + tag

### ISSUE THREAD

**Issue by justindh** [recursivetree/seat-info#3]
Would you be open to implementing 

https://www.npmjs.com/package/shipfit

and the <shipfit> tag?

**Comment by recursivetree** [comment]
this is a good idea, I'll look into it.

Just to make sure, do you know about the seat-fitting plugin? If you intend to use seat-info as a fitting/doctrine storage, seat-fitting might be better, as it e.g. allows you to view corp members with the skills to fly a fit

**Comment by recursivetree** [comment]
![Bildschirmfoto 2022-10-07 um 15 06 30](https://user-images.githubusercontent.com/60423027/194560853-99d8cdea-69c1-4b13-aa17-4ed785f40204.png)
What do you think?
