### ISSUE TITLE
Adding Plugin Causes Docker Environment Load Failure

### ISSUE THREAD

**Issue by DIRVINE4** [recursivetree/seat-info#4]
Added this plugin into the .env using =recursivetree/seat-info; =recursivetree/seat-info:2.0.1; and =recursivetree/seat-info:2.0.0. After down/up'ing the docker environment, SeAT would not load with a Bad Gateway error and eventually a 404 error. 

Below is an example of the plugin area of the .env file. I'm using.

```
# ---------------------------
# Plugins Section
# ---------------------------

# This is a list of the all of the third party plugins that you
# would like to install as part of SeAT. Package names should be
# comma seperated if multiple packages should be installed.
SEAT_PLUGINS=cryptatech/seat-fitting:5.0.5,cryptatech/seat-srp:5.0.4,recursivetree/seat-info #:2.0.1 :2.0.0
#,crypta-tech/seat-srp:5.0.4,recursivetree/seat-info:5.0.4
#SEAT_PLUGINS=vendor1/package
#SEAT_PLUGINS=vendor1/package,vendor2/package

```

**Comment by recursivetree** [comment]
Can you send me the logs of the stack starting up? Otherwise I can't tell what is going wrong.

**Comment by DIRVINE4** [comment]
For sure! One sec! I'll edit this comment.

After glancing at my logs I noticed that my docker containers weren't up to date. If anyone is having this issue, run the commands for your install listed here: https://eveseat.github.io/docs/upgrading/general/

Sorry about that, dev. It's working now!

**Comment by DIRVINE4** [comment]
Issue solved by upgrading my docker environment.
